= CloudBees action: ServiceNow operations

Use this action to perform the following ServiceNow operations using the CloudBees platform: 

* xref:README.adoc#create-a-change-request[Create a change request].
* xref:README.adoc#update-or-close-a-change-request[Update or close a change request].
* xref:README.adoc#get-the-current-state-of-a-change-request[Get the current state of a change request].

== Authentication methods

The ServiceNow action supports both basic and OAuth authentication methods to connect with ServiceNow.

* *Basic authentication*: Provide a ServiceNow URL, a valid username, and a password to connect to the ServiceNow application.
* *OAuth authentication*: In addition to a ServiceNow URL, a valid username, and a password, provide a *ClientId* and *Client Secret*, for generating a bearer access token with an expiration date.
This method is more secure.

== Supported versions

CloudBees has tested and supports the following ServiceNow releases:

* link:https://www.servicenow.com/docs/bundle/xanadu-release-notes/page/release-notes/family-release-notes.html[Xanadu]
* link:https://www.servicenow.com/docs/bundle/washingtondc-release-notes/page/release-notes/family-release-notes.html[Washington DC]
* link:https://www.servicenow.com/docs/bundle/vancouver-release-notes/page/release-notes/family-release-notes.html[Vancouver]

Other versions of ServiceNow may work with the CloudBees platform.
If you are using a version of ServiceNow not listed above, submit a feature request with link:https://support.cloudbees.com[CloudBees Support].

== Create a change request

Use this functionality to create a new change request in ServiceNow.
The user must provide:

* xref:README.adoc#authentication-methods[Valid credentials] and the ServiceNow host URL.
* The *create* action type.

=== Inputs

Inputs for the create change request functionality are listed below.

[cols="3a,2a,3a,5a",options="header"]
.Input details
|===

| Change request model field
| Data type
| Required?
| Description

| `action-type`
| String
| Yes
| The operation type must be "create".

| `url`
| String
| Yes
| The ServiceNow host URL.

| `username`
| String
| Yes
| The username used for authentication.

| `password`
| String
| Yes
| The password used for authentication.

| `client-id`
| String
| Required only for OAuth-based authentication.
| The unique identification number of the client.

| `client-secret`
| String
| Required only for OAuth-based authentication.
| The client secret for authentication.

| `short-description`
| String
| No
| A brief title to identify the change request.

| `long-description`
| String
| No
| Additional information about the change request ticket.

| `cr-type`
| String
| No
| The type of change request.
The default value is "normal".

| `state`
| String
| No
| The current status of the change request.

| `priority`
| String
| No
| The priority of the change request.

| `risk`
| String
| No
| The risk involved in the change request.

| `impact`
| String
| No
| The impact of the change request.

| `category`
| String
| No
| The change request ticket category.

| `requested-by`
| String
| No
| The user that requested the change.

| `assignment-group`
| String
| No
| The assignment group to which the change request must be mapped.

| `assigned-to`
| String
| No
| The user to whom the change request ticket must be assigned in the assignment group.

| `validate-blackout-window-conflict`
| Boolean
| No
| Whether to check if there is a blackout window conflict.
The default value is false.

| `planned-start-date`
| String
| Required if `validate-blackout-window-conflict` is true.
| The scheduled start date and time of the change request, formatted as `yyyy-mm-dd hh:mm:ss`.

| `planned-end-date`
| String
| Required if `validate-blackout-window-conflict` is true.
| The scheduled end date and time of the change request, formatted as `yyyy-mm-dd hh:mm:ss`.

| `additional-parameters`
| JSON string
| No
| Any additional parameters apart from the list provided above.
Refer to link:https://www.servicenow.com/docs/bundle/xanadu-api-reference/page/integrate/inbound-rest/concept/change-management-api.html#title_change-GET-change-sys_id[the ServiceNow documentation] for more information.

|===

== Unique identifiers generated by ServiceNow

Unique `cr-number` and `sys_id` identifiers are generated by ServiceNow when the ticket is successfully created.

* The `sys_id` is a unique 32-character identifier required to xref:README.adoc#update-or-close-a-change-request[update or close] the ticket.
* The `cr-number` is required to xref:README.adoc#get-the-current-state-of-a-change-request[get the current state] of a change request and to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/service-now/poll-for-approval[query a change request for approval].

=== Outputs

The following outputs are generated when creating a change request:

[cols="3a,2a,5a",options="header"]
.Output details
|===

| Change request model field
| Data type
| Description

| `number`
| String
| The unique change request number auto-generated during change request creation.

| `sys_id`
| String
| The identifier auto-generated during change request creation.

| `state`
| String
| The current status of the change request.

|===


=== Usage examples: Create a change request

The following is an example payload for creating a change request using basic authentication:

[source,yaml,role="default-expanded"]
----

    steps:
      - name: Create ServiceNow CR with basic auth
        id: create_cr
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: "create"
          cr-type: "normal"
          short-description: "Title of the CR ticket"

----

If your workflow uses a link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/manage-workflows#create-trigger[manual trigger], you can configure input parameters for the ServiceNow change request fields in the format `${{ inputs.MY_PARAMETER }}`, which can then be passed to the action inputs.
The following is an example payload for creating a change request using basic authentication and input parameters:

[source,yaml,role="default-expanded"]
----

    steps:
      - name: Create ServiceNow CR with manual trigger
        id: create_cr
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: create
          cr-type: Normal
          short-description: ${{ inputs.Short_Description }}
          description: ${{ inputs.Description }}

----

=== Check for a blackout window

If the parameter `validate-blackout-window-conflict` is set to true, the action performs an additional check before creating the change request.

When this parameter is set to true, you must input both planned start and end dates and times.
The action checks ServiceNow for the configuration of a blackout window during the planned start and end dates provided in the change request.

* If a blackout window exists during the scheduled dates, then the action fails and the change request is not created.
* If no blackout window conflict is detected, the action then creates the change request.

The following is an example payload for creating a change request using OAuth-based authentication and checking for any blackout windows within the planned change request start and end dates:

[source,yaml,role="default-expanded"]
----

    steps:
      - name: Create ServiceNow CR and check for a blackout window
        id: create_cr
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ vars.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          client-id: ${{ secrets.MY_CLIENT_ID }}
          client-secret: ${{ secrets.MY_CLIENT_SECRET }}
          action-type: create
          cr-type: Normal
          short-description: 'check for blackout window'
          validate-blackout-window-conflict: true
          planned-start-date: "2025-03-06 17:00:00"
          planned-end-date: "2025-03-06 17:59:59"

----

NOTE: Times specified in the `planned-start-date` and `planned-end-date` fields are evaluated to be in the UTC time zone by default. If the time zone is already configured in the ServiceNow instance, then the fields are evaluated to be in the ServiceNow-configured time zone.

== Update or close a change request

Use this functionality to update or close an existing ServiceNow change request.
The user must provide:

* xref:README.adoc#authentication-methods[Valid credentials] and the ServiceNow host URL.
* The *update* action type.
* The unique *sys_id* attribute returned by the change request response.

=== Inputs

Inputs for the change request functionality are listed below.

[cols="3a,2a,4a,5a",options="header"]
.Input details
|===

| Change request model field
| Data type
| Required
| Description

| `url`
| String
| Yes
| The ServiceNow host URL.

| `username`
| String
| Yes
| The username used for authentication.

| `password`
| String
| Yes
| The password used for authentication.

| `client-id`
| String
| Required only for OAuth-based authentication.
| The unique identification number of the client.

| `client-secret`
| String
| Required only for OAuth-based authentication.
| The client secret for authentication.

| `action-type`
| String
| Yes
| The type of operation is "update" for both updating and closing a change request.

| `sys-id`
| String
| Yes
| The identifier auto-generated during xref:README.adoc#unique-identifiers-generated-by-servicenow[change request creation].

| `close-code`
| String
| Required for the close operation only if configured as mandatory fields in ServiceNow for closing a ticket.
| The code assigned to the change request by the user closing it. 
For example, "successful", "successful with issues", or "unsuccessful".

| `close-notes`
| String
| Required for the close operation only if configured as mandatory fields in ServiceNow for closing a ticket.
| The notes entered by the user closing the change request.

| `short-description`
| String
| No
| A short title for easy identification.

| `description`
| String
| No
| Additional information about the change request ticket.

| `cr-type`
| String
| No
| The type of change request.
The default value is "normal".

| `state`
| String
| No
| The current status of the change request (matches the ServiceNow configuration).

| `priority`
| String
| No
| The priority of the change request.

| `risk`
| String
| No
| The risk involved in the change request.

| `impact`
| String
| No
| The impact of the change request.

| `category`
| String
| No
| The change request ticket category.

| `requested-by`
| String
| No
| The user that requested the change.

| `assignment-group`
| String
| No
| The assignment group to which the change request must be mapped.

| `assigned-to`
| String
| No
| The user to whom the change request ticket must be assigned in the assignment group.

| `additional-parameters`
| JSON String
| No
| Any additional parameters apart from the list provided above.
Refer to link:https://www.servicenow.com/docs/bundle/xanadu-api-reference/page/integrate/inbound-rest/concept/change-management-api.html#title_change-GET-change-sys_id[the ServiceNow documentation] for more information.

|===


=== Outputs

Outputs for the update change request functionality are listed below.

[cols="3a,2a,5a",options="header"]
.Output details
|===

| Change request model field
| Data type
| Description

| `sys_id`
| String
| The identifier used for change request updates.

| `state`
| String
| The current status of the change request.

|===


=== Usage example: Update a change request

The following is an example payload for updating a change request using basic authentication:

[source,yaml,role="default-expanded"]
----
      - name: Update ServiceNow CR with basic auth
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: "update"
          sys-id: "the unique system-generated string"
          description: "Updated description from CBP workflow"
          priority: "3 - Moderate"
          risk: "Low"
          additional-parameters : '{"risk_impact_analysis":"Describe the risks here","implementation_plan": "Describe the implementation plan here"}'
----

The following is an example payload referring to the output parameter `sys_id` from the link:https://github.com/cloudbees-io/servicenow/blob/main/README.adoc#create-a-change-request[change request creation] step as input in the update step:

[source,yaml,role="default-expanded"]
----
      - name: Update ServiceNow CR with output parameter ref
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: "update"
          sys-id: ${{ fromJSON(steps.create_cr.outputs.servicenow_output).sys_id }}
          description: "Updated description from CBP workflow"
          priority: "3 - Moderate"
          risk: "Low"
          additional-parameters : '{"risk_impact_analysis":"Describe the risks here","implementation_plan": "Describe the implementation plan here"}'
----


=== Usage example: Close a change request

The following is an example payload for closing a change request:

[source,yaml,role="default-expanded"]
----
      - name: Close ServiceNow CR with mandatory close fields
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ vars.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          client-id: ${{ secrets.MY_CLIENT_ID }}
          client-secret: ${{ secrets.MY_CLIENT_SECRET }}
          action-type: "update"
          sys-id: "Unique ServiceNow-generated identifier"
          state: "close"
          close-code: "successful"
          close-notes: "Change request closed in successful state"

----

The following is an example payload referring to the output parameter `sys_id` from the link:https://github.com/cloudbees-io/servicenow/blob/main/README.adoc#create-a-change-request[change request creation] step as input in the close step:

[source,yaml,role="default-expanded"]
----
      - name: Close ServiceNow CR with output parameter ref
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          client-id: ${{ secrets.MY_CLIENT_ID }}
          client-secret: ${{ secrets.MY_CLIENT_SECRET }}
          action-type: "update"
          sys-id: ${{ fromJSON(steps.create_cr.outputs.servicenow_output).sys_id }}
          state: "close"
          close-code: "successful"
          close-notes: "Change request closed in successful state"
----

[NOTE]
====

For information about using input parameters in a manually triggered workflow, refer to the link:https://github.com/cloudbees-io/servicenow/blob/main/README.adoc#create-a-change-request[change request] usage examples.

====

== Get the current state of a change request

Use this functionality to get the current state, including any blackout window conflict status, of a ServiceNow change request.
The user must provide:

* xref:README.adoc#authentication-methods[Valid credentials] and the ServiceNow host URL. 
* The *get* action type.
* The *cr-number* auto-generated during change request creation.

== Inputs

Inputs for the Get Change request functionality are listed below.

[cols="3a,3a,4a,5a",options="header"]
.Input details
|===

| Change request model field
| Data type
| Required
| Description

| `url`
| String
| Yes
| The ServiceNow host URL.

| `username`
| String
| Yes
| The username used for authentication.

| `password`
| String
| Yes
| The password used for authentication.

| `client-id`
| String
| Required only for OAuth-based authentication.
| The unique identification number of the client.

| `client-secret`
| String
| Required only for OAuth-based authentication.
| The client secret for authentication.

| `action-type`
| String
| Yes
| The type of operation must be "get".

| `cr-number`
| String
| Yes
| The unique number auto-generated during xref:README.adoc#unique-identifiers-generated-by-servicenow[change request creation].

|===


=== Outputs

Outputs for the get change request functionality are listed below.

[cols="3a,2a,5a",options="header"]
.Output details
|===

| Change request model field
| Data type
| Description

| `number`
| String
| The change request number.

| `sys_id`
| String
| The identifier used to update the change request.

| `state`
| String
| The current status of the change request.

| `conflict_status`
| String
| The current conflict status of the planned dates.

|===

=== Usage examples: Get the current state

The following is an example payload with basic authentication to get the current change request state:

[source,yaml,role="default-expanded"]
----

    steps:
      - id: get
        name: Get ServiceNow CR state with basic auth
        uses: https://github.com/cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ vars.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: "get"
          cr-number: "Unique ServiceNow-generated number"

----

The following is an example payload referring to the output parameter `number` from the link:https://github.com/cloudbees-io/servicenow/blob/main/README.adoc#create-a-change-request[change request creation] step as input in the get step:

[source,yaml,role="default-expanded"]
----

    steps:
      - name: update ServiceNow CR with basic auth
        uses: cloudbees-io/service-now@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ vars.MY_SERVICENOW_USERNAME }}
          password: ${{ secrets.MY_SERVICENOW_PASSWORD }}
          action-type: "update"
          sys-id: ${{ fromJSON(steps.get.outputs.servicenow_output).number }}
          description: "Updated description from CBP workflow"

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
